####################
#   Your Profile   #
####################
title: nice food
name: Names
glad_text: your blog glad text
lang: zh-cn
email: ztd811@qq.com
description: your description
twitter_username: ztd811
github_username:  mba811
disqus:

show-about: true
about-title: Introduce My Self
about-description: this post contain resume
about-image: /assets/images/covers/telephone-pole.jpg

###############
#    build    #
###############
baseurl: ""
imageurl: "/assets/images"
url: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag