####################
#   Your Profile   #
####################
title: Nice Food
name: Tsong Khapa
glad_text: Hello ，欢迎访问 Tsong Khapa‘s Photo and Album
lang: zh_CN
email: ztd811@qq.com
description: Hello ，Welcome to Tsong Khapa‘s Photo and Album
twitter_username: ztd811
github_username: mba811
disqus: 

show-about: true
about-title: Introduce My Self
about-description: this post contain resume
about-image: /assets/images/covers/telephone-pole.jpg

###############
#    build    #
###############
baseurl: ""
imageurl: "/assets/images"
url: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag